######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 2 16:56:07 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += \
           bms.h \
           charge.h \
           config.h \
           error.h \
           Hachiko.h \
           log.h
SOURCES += bms.c config.c Hachiko.c log.c tom.c

LIBS += -lrt
